# Generated by Django 3.0.5 on 2020-04-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
            ],
        ),
    ]
